name: Generate Feeds
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkuout Repo
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Insall dependencies
        run: |
          python -m pip install upgrade pip
          pip install pyyaml
      - name: Feed generator
        run: python feed.py
      - name: Push Repo
        run: |
          git config user.name Priyanka
          git config user.email priyanka.dubey@gmail.com
          git .add
          git -m "Modified Feed"
          git push
          
